import { LegalFooter } from "@/components/LegalFooter";

export const metadata = {
  title: "Terms of Service | EMI & Loan Calculator",
  description: "Terms of Service for the EMI & Loan Calculator tool.",
};

export default function TermsPage() {
  return (
    <main className="container mx-auto max-w-3xl px-4 py-12 space-y-6">
      <h1 className="text-3xl font-bold">Terms of Service</h1>

      <p className="text-muted-foreground">
        By accessing and using the EMI & Loan Calculator website, you agree to
        comply with and be bound by these Terms of Service.
      </p>

      <h2 className="text-xl font-semibold">Use of the Calculator</h2>
      <p>
        This calculator is provided for general informational purposes only.
        All calculations are estimates and may not reflect actual loan offers,
        terms, or conditions provided by financial institutions.
      </p>

      <h2 className="text-xl font-semibold">No Financial Advice</h2>
      <p>
        The content and results generated by this website do not constitute
        financial, legal, or professional advice. Users should consult qualified
        financial professionals before making any financial decisions.
      </p>

      <h2 className="text-xl font-semibold">User Responsibility</h2>
      <p>
        You acknowledge that your use of this website and reliance on any
        information provided is at your own discretion and risk.
      </p>

      <h2 className="text-xl font-semibold">Limitation of Liability</h2>
      <p>
        We shall not be held liable for any direct, indirect, incidental, or
        consequential damages arising from the use of this website or reliance
        on the calculation results.
      </p>

      <h2 className="text-xl font-semibold">Changes to These Terms</h2>
      <p>
        These Terms of Service may be updated from time to time. Continued use
        of the website after changes are posted constitutes acceptance of the
        revised terms.
      </p>

      {/* Back to Home */}
      <LegalFooter />
    </main>
  );
}
