import { LegalFooter } from "@/components/LegalFooter";

export const metadata = {
  title: "Disclaimer | EMI & Loan Calculator",
  description: "Financial disclaimer for the EMI & Loan Calculator tool.",
};

export default function DisclaimerPage() {
  return (
    <main className="container mx-auto max-w-3xl px-4 py-12 space-y-6">
      <h1 className="text-3xl font-bold">Disclaimer</h1>

      <p className="text-muted-foreground">
        The information provided by the EMI & Loan Calculator is for general
        informational and educational purposes only.
      </p>

      <p>
        All calculation results are estimates and should not be considered as
        exact figures or financial advice. Actual loan terms, interest rates,
        fees, and repayment schedules may vary depending on the lender, market
        conditions, and individual borrower profile.
      </p>

      <p>
        This website does not provide financial, legal, or professional advice.
        Users are encouraged to consult qualified financial professionals or
        lenders before making any financial decisions.
      </p>

      <p>
        We make no warranties or guarantees regarding the accuracy, completeness,
        or reliability of the calculation results generated by this tool.
      </p>

      <p>
        By using this website, you acknowledge that any reliance on the
        information provided is strictly at your own risk.
      </p>

      {/* Back to Home */}
      <LegalFooter />
    </main>
  );
}
